branch-defaults:
  master:
    environment: test3
    group_suffix: null
global:
  application_name: dockertest
  branch: null
  default_ec2_keyname: ehla_frontend_key2
  default_platform: Docker 17.03.2-ce
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
